- defaults:
    link:
      relink: true

# - clean: ['~']

- create:
  - ~/Library/KeyBindings/

- link:
    ~/.asdfrc: asdfrc
    ~/.curlrc: curlrc
    ~/.config/:
      path: config/*
      glob: true
      create: true
    ~/.gitconfig:
    ~/.gitconfig.platform:
      if: '[ `uname` = Darwin ]'
      path: gitconfig.platform.darwin
    ~/.git-prompt.sh:
    ~/.iex.exs:
    ~/.pryrc:
    ~/.rspec:
    ~/.tmate.conf:
    ~/.tmux.conf:
    ~/.vimrc:
    ~/.zprofile:
    ~/.zlogin:
    ~/.zshrc:
    ~/.p10k.zsh:
    ~/Library/KeyBindings/DefaultKeyBinding.dict:
      if: '[ `uname` = Darwin ]'
      path: osx/custom_keybinding.dict
    ~/Library/Application Support/iTerm2/DynamicProfiles/dynamic_profile.json:
      if: '[ `uname` = Darwin ]'
      path: iterm2/dynamic_profile.json
    ~/Library/Application Support/Code/User/:
      if: '[ `uname` = Darwin ]'
      path: vscode/*
      glob: true
    ~/.dotfiles/zsh/custom/plugins/onelogin_aws:
      path: dotfiles_per_company/onelogin_aws/
    # ~/.tmux.conf: tmux.conf
    # ~/.vim: vim

# - shell:
#   - [git submodule update --init --recursive, Installing submodules]
#   - [cat vscode/extension_list.txt | xargs -n 1 code --install-extension, Installing vscode extensions]
